services:
  planificador-api:
    container_name: planificador-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./backend/data:/app/data
    expose:
      - "3001"

  planificador-web:
    container_name: planificador
    build:
      context: .
      dockerfile: Dockerfile
      args:
        REACT_APP_FIREBASE_API_KEY: ${REACT_APP_FIREBASE_API_KEY}
        REACT_APP_FIREBASE_AUTH_DOMAIN: ${REACT_APP_FIREBASE_AUTH_DOMAIN}
        REACT_APP_FIREBASE_PROJECT_ID: ${REACT_APP_FIREBASE_PROJECT_ID}
        REACT_APP_FIREBASE_STORAGE_BUCKET: ${REACT_APP_FIREBASE_STORAGE_BUCKET}
        REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${REACT_APP_FIREBASE_MESSAGING_SENDER_ID}
        REACT_APP_FIREBASE_APP_ID: ${REACT_APP_FIREBASE_APP_ID}
        REACT_APP_FIREBASE_MEASUREMENT_ID: ${REACT_APP_FIREBASE_MEASUREMENT_ID}
    depends_on:
      - planificador-api
    ports:
      - "8086:80"
    restart: unless-stopped
